[versions]
androidGradlePlugin = "8.13.0"
appcompat = "1.7.1"
material = "1.13.0"
junit = "4.13.2"
extJunit = "1.3.0"
espressoCore = "3.7.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }